# Generated by Django 4.2.7 on 2023-11-24 07:33

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('file', '0006_colortag_colortaggeditem_alter_file_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colortaggeditem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='colortaggeditem',
            name='tag',
        ),
        migrations.AlterField(
            model_name='file',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='ColorTag',
        ),
        migrations.DeleteModel(
            name='ColorTaggedItem',
        ),
    ]
