# Generated by Django 4.2.7 on 2023-12-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_colortag_colortaggeditem_alter_file_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.BinaryField(),
        ),
    ]
