# Generated by Django 4.2.1 on 2023-11-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_name_user_first_name_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
