# Generated by Django 4.2.1 on 2023-11-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_b64',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
