# Generated by Django 4.2.1 on 2023-11-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_image_b64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_b64',
        ),
    ]
