# Generated by Django 4.2.7 on 2023-11-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_auto_20190629_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
